services:

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/mydatabase?authSource=admin
    ports:
      - 8082:8080
    depends_on:
      - mongodb

  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    environment:
      MONGODB_DATABASE: mydatabase
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
